#spring.application.name=spring-batch-upload-tas-betc-api
server:
  port: 8086
  servlet:
    context-path: /tas-betc-api

spring:
  datasource:
    url: jdbc:h2:mem:public;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  main:
    banner-mode: off
  jmx:
    default-domain: /tas-betc-api
  jpa:
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        default_schema: public
        show_sql: true
    show-sql: true
